all:Score_Board Desk Player

Score_Board:Score_Board.o
	gcc -o Score_Board Score_Board.o -lm

Score_Board.o:Score_Board.c
	gcc -c Score_Board.c

Desk:Desk.o
	gcc -o Desk Desk.o -lm

Desk.o:Desk.c
	gcc -c Desk.c

Player:Player.o
	gcc -o Player Player.o -lm

Player.o:Player.c
	gcc -c Player.c

